### PR TITLE
protoc-gen-go-drpc: allow to generate service files to dedicated dir

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
this is similar pr for drpc generator as like in grpc-go https://github.com/grpc/grpc-go/pull/5255

**Comment by vtolstov** [comment]
mostly this is needed to split generated code from generated protobuf messages code

**Comment by vtolstov** [comment]
also with this changes you can rename client and server interfaces do not have prefix DRPC

**Comment by vtolstov** [comment]
@zeebo any chance to get this merged?
my use-case - split all generated code for grpc, drpc in different dirs

**Comment by zeebo** [comment]
Sorry I missed all this. Taking a look now.

**Comment by zeebo** [comment]
So I took a look at the grpc PR, and they had some concerns about the import path. Until that's resolved, can we make this an "unstable_standalone" flag or something?

**Pull request closed without merging**
